# Drops existing tables, recreates them and executes import.sql
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  # Settings for the oracle connection
  datasource:
    url:
      jdbc:oracle:thin:@localhost:1521:xe
    username:
      system
    password:
      root
    driver-class-oracle:
      jdbc:
        driver:
          OracleDriver